
# Keyboard backlight
listener {
    timeout = 150                                # 2.5 min
    on-timeout = sh -c 'if ! playerctl status 2>/dev/null | grep -q Playing; then brightnessctl -sd rgb:kbd_backlight set 0; fi'
    on-resume = brightnessctl -rd rgb:kbd_backlight
}

# Lock screen
listener {
    timeout = 300
    on-timeout = sh -c 'if ! playerctl status 2>/dev/null | grep -q Playing; then pidof hyprlock >/dev/null || hyprlock; fi'
}

# "screen off" simulation (lock + brightness=0)
listener {
    timeout = 330
    on-timeout = sh -c 'if ! playerctl status 2>/dev/null | grep -q Playing; then brightnessctl -s set 0; fi'
    on-resume = brightnessctl -r
}

