# ░█░█░█░█░█▀█░█▀▄░░░█░█░█▀█░█▀▄░▀█▀░█▀█░█▀▄░█░░░█▀▀░█▀▀
# ░█▀█░░█░░█▀▀░█▀▄░░░▀▄▀░█▀█░█▀▄░░█░░█▀█░█▀▄░█░░░█▀▀░▀▀█
# ░▀░▀░░▀░░▀░░░▀░▀░░░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀░░▀▀▀░▀▀▀░▀▀▀

$mainMod            = SUPER

$terminal           = foot
$editor             = foot -e --override=colors.alpha=1 nvim
$fileManager        = foot -e yazi
$musicPlayer        = foot -e rmpc
$menu               = pkill rofi || zsh -i -c 'rofi -show drun' 
$rmenu              = pkill rofi || zsh -ic '~/.config/scripts/launchrofi -r'
$clipboard          = rofi -modi Clipboard:~/.config/hypr/scripts/clipboard.sh -show Clipboard -show-icons
$browser            = bash ~/.config/hypr/scripts/openBrowser.sh 
$loginManager       = hyprlock
$screenshot         = ~/.config/scripts/launchrofi --screenshot_menu

