# ░█░█░█░█░█▀█░█▀▄░░░█░█░█▀█░█▀▄░▀█▀░█▀█░█▀▄░█░░░█▀▀░█▀▀
# ░█▀█░░█░░█▀▀░█▀▄░░░▀▄▀░█▀█░█▀▄░░█░░█▀█░█▀▄░█░░░█▀▀░▀▀█
# ░▀░▀░░▀░░▀░░░▀░▀░░░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀░░▀▀▀░▀▀▀░▀▀▀

$mainMod            = SUPER

$terminal           = foot
$editor             = foot -e --override=colors.alpha=1 nvim
$fileManager        = foot -e yazi
$musicPlayer        = foot -e rmpc
$menu               = pkill rofi || rofi -show drun 
$rmenu              = pkill rofi || ~/.config/hypr/scripts/rofilaunch.sh --run
$clipboard          = rofi -modi Clipboard:~/.config/hypr/scripts/clipboard.sh -show Clipboard -show-icons
$browser            = bash ~/.config/hypr/scripts/openBrowser.sh 
$loginManager       = hyprlock
$screenshot         = hyprshot-gui
