#!/usr/bin/env bash

cd ~

# Usage Information
usage() {
    echo -e "\n Usage:
      --drun     : Launches the application launcher (drun).\n
      --run      : Launches the command runner (run). \n
      --menu     : Displays a custom menu with multiple options. \n
      --window   : Displays a open windows.\n 
      --sys_menu : Displays system menu. \n"
    exit 1
}

# Function: DRUN Launcher
drun_launcher() {
    rofi \
        -show drun
}

# Function: RUN Launcher
run_launcher() {
    rofi \
        -show run \
        -theme ~/.config/rofi/launcher.rasi
}

# Function: CONFIRMATION Launcher
conf_launcher() {
    rofi \
    -show run \
    -theme ~/.config/rofi/confirm.rasi
}

# Function: Custom Menu
custom_menu() {
    # Menu options displayed in rofi
    options="\n\n\n\n\n"

    # Prompt user to choose an option
    chosen=$(echo -e "$options" | rofi -config ~/.config/rofi/submenu.rasi -dmenu  -theme-str 'mainbox {children: ["listview" ];}' -p "")

    # Execute the corresponding command based on the selected option
    case $chosen in
        "")
            rofi -show drun
            ;;
        "")
            thunar
            ;;
        "")
            session_options
            ;;
        "")
            foot
            ;;
        "")
            bash ~/.config/hypr/scripts/openBrowser.sh
            ;;
        "")
        manual_func
            ;;
        *)
            echo "No option selected"
            ;;
    esac
}

session_options() {
    # Menu options displayed in rofi
    options="  Shutdown\n  Reboot\n  Lock\n󰍃  Logout"

    # Prompt user to choose an option
    chosen=$(echo -e "$options" | rofi -config ~/.config/rofi/sysmenu.rasi -dmenu -theme-str 'listview {lines: 4;}' -theme-str 'window {width: 285px;}' -theme-str 'mainbox {children: ["listview" ];}' -p "")

    # Execute the corresponding command based on the selected option
    case $chosen in
        "󰌍")
            system_menu
            ;;
        "  Shutdown")
            notify-send 'Shutting down...' & systemctl poweroff
            ;;
        "  Reboot")
            systemctl reboot
            ;;

        "  Lock")
            hyprlock & disown
            ;;
        "󰍃  Logout")
            notify-send 'Logging out...'&hyprctl dispatch exit 0
            ;;
        *)
            echo "No option selected"
            ;;
    esac
}


widget_settings() {
    # Menu options displayed in rofi
    options="󰌍\n  Desk Clock\n  Change Stats\n  Change Music\n  Reload Widgets\n  Initalize"

    # Prompt user to choose an option
    chosen=$(echo -e "$options" | rofi -config ~/.config/rofi/sysmenu.rasi -dmenu -p "")

    # Execute the corresponding command based on the selected option
    case $chosen in
        "󰌍")
            rice_settings
            ;;
        "  Desk Clock")
            bash ~/.config/hypr/scripts/widgets.sh three
            bash ~/.config/hypr/scripts/widgets.sh r >/dev/null 2>&1 & disown
            widget_settings
            ;;
        "  Change Stats")
            bash ~/.config/hypr/scripts/widgets.sh one
            bash ~/.config/hypr/scripts/widgets.sh r >/dev/null 2>&1 & disown
            widget_settings
            ;;
        "  Change Music")
            bash ~/.config/hypr/scripts/widgets.sh two
            bash ~/.config/hypr/scripts/widgets.sh r >/dev/null 2>&1 & disown
            widget_settings
            ;;
        "  Reload Widgets")
            bash ~/.config/hypr/scripts/widgets.sh r >/dev/null 2>&1 & disown
            widget_settings
            ;;
        "  Initalize Widgets")
            bash ~/.config/hypr/scripts/widgets.sh r >/dev/null 2>&1 & disown
            widget_settings
            ;;
        *)
            echo "No option selected"
            ;;
    esac
}

rice_settings() {
    # Menu options displayed in rofi
    options="󰌍\n  Activate Linux\n  Toggle Widgets\n  Wallpaper\n󰌁  Themes"

    # Prompt user to choose an option
    chosen=$(echo -e "$options" | rofi -config ~/.config/rofi/sysmenu.rasi -dmenu -p "")

    # Execute the corresponding command based on the selected option
    case $chosen in
        "󰌍")
            system_menu
            ;;
        "  Activate Linux")
            bash ~/.config/hypr/scripts/widgets.sh four
            bash ~/.config/hypr/scripts/widgets.sh r >/dev/null 2>&1 & disown
            rice_settings
            ;;
        "  Toggle Widgets")
            widget_settings
            ;;
        "󰌁  Themes")
            theme_menu
            ;;
        "  Wallpaper")
            set_wallpaper
            ;;
        *)
            echo "No option selected"
            ;;
    esac
}

set_wallpaper() {

    # Prompt user to choose an option
    chosen=$(python ~/.config/hypr/scripts/wallpapers.py echoImageNames | rofi -config ~/.config/rofi/sysmenu.rasi -dmenu -theme-str 'mainbox {children: ["inputbar","listview" ];}'  -p "")
    # Execute the corresponding command based on the selected option
    echo $chosen
    python ~/.config/hypr/scripts/wallpapers.py changeWallpaper $chosen
}

maintain_menu() {
    # Menu options displayed in rofi
    options="󰌍\n󰃢  Clear Cache\n󱘡  Clear Clipboard\n󰚰  Update Rice"

    # Prompt user to choose an option
    chosen=$(echo -e "$options" | rofi -config ~/.config/rofi/sysmenu.rasi -dmenu -theme-str 'listview {lines: 6;}' -p "")

    # Execute the corresponding command based on the selected option
    case $chosen in
        "󰌍")
            system_menu
            ;;

        "󰃢  Clear Cache")
         	find ~/.cache -mindepth 1 -maxdepth 1 \
         	  ! -name "spotify" \
         	  ! -name "cliphist" \
         	  ! -name "paru" \
         	  ! -name "mcpelauncher-webview"\
         	  ! -name "pip" \
         	  ! -name "rofi-entry-history.txt" \
         	  ! -name "Hyprland Polkit Agent" \
         	  ! -name "spotube" \
         	  ! -name "oss.krtirtho.spotube" \
         	  -exec rm -rf {} + >/dev/null 2>&1 & disown
            maintain_menu
            ;;
        "󱘡  Clear Clipboard")
            rm -rf ~/.cache/cliphist >/dev/null 2>&1 & disown
            maintain_menu
            ;;
        "󰚰  Update Rice")
            curl -sSL https://raw.githubusercontent.com/BinaryHarbinger/hyprdots/refs/heads/main/install.sh -o install.sh
            foot --override=colors.alpha=1 --app-id=Update -e bash ./install.sh
            rm -rf ./install.sh
                    ;;
        *)
            echo "No option selected"
            ;;
    esac
}

manual_func() {
    # Menu options displayed in rofi
    options="󰌍\n  Keybinds"

    # Prompt user to choose an option
    chosen=$(echo -e "$options" | rofi -config ~/.config/rofi/sysmenu.rasi -dmenu -p "")

    # Execute the corresponding command based on the selected option
    case $chosen in
        "󰌍")
            system_menu
            ;;
        "  Keybinds")
            rofi -dmenu -theme-str 'window {width: 52%;}' -dmenu -theme-str 'listview {lines: 14;}' -i -p ' ' < ~/.config/hypr/scripts/help.txt
            ;;
        *)
            echo "No option selected"
            ;;
    esac
}

screenshot_func() {
    # Menu options displayed in rofi
    options="󰌍\n  Screenshots\n  Fullscreen\n  Selection"

    # Prompt user to choose an option
    chosen=$(echo -e "$options" | rofi -config ~/.config/rofi/sysmenu.rasi -dmenu -theme-str 'listview {lines: 6;}' -p "")

    # Execute the corresponding command based on the selected option
    case $chosen in
        "󰌍")
            system_menu
            ;;
        "  Screenshots")
            foot -e yazi ~/Pictures/Screenshots/
            ;;
        "  Fullscreen")
            hyprshot -m output -o ~/Pictures/Screenshots && notify-send -i camera "Hyprshot" "Saved to ~/Pictures/Screenshots"
            ;;
        "  Selection")
            hyprshot -m region -o ~/Pictures/Screenshots && notify-send -i camera "Hyprshot" "Saved to ~/Pictures/Screenshots"
            ;;
        *)
            echo "No option selected"
            ;;
    esac
}

connections_func() {
    # Menu options displayed in rofi
    options="󰌍\n󰤨  WiFi\n  Bluetooth (WIP)"

    # Prompt user to choose an option
    chosen=$(echo -e "$options" | rofi -config ~/.config/rofi/sysmenu.rasi -dmenu -theme-str 'listview {lines: 6;}' -p "")

    # Execute the corresponding command based on the selected option
    case $chosen in
        "󰌍")
            system_menu
            ;;
        "󰤨  WiFi") 
            bash ~/.config/hypr/scripts/rofiwifi.sh
            ;;
        " Bluetooth")
            
            ;;
        *)
            echo "No option selected"
            ;;
    esac
}

system_menu() {
    # Menu options displayed in rofi
    options="  Apps\n  Connections\n󰃢  Maintaining\n󰅇  Clipboard\n󰄀  Screenshot\n  Session Options\n  Manual\n  Settings\n  Update System"

    # Prompt user to choose an option
    chosen=$(echo -e "$options" | rofi -config ~/.config/rofi/sysmenu.rasi -dmenu -theme-str 'listview {lines: 9;}' -theme-str 'mainbox {children: ["inputbar","listview" ];}'  -p "")

    # Execute the corresponding command based on the selected option
    case $chosen in
        "  Apps")
            drun_launcher
            ;;
        "  Connections")
            connections_func
            ;;
        "󰃢  Maintaining")
            maintain_menu
            ;;
        "󰅇  Clipboard")
            rofi -modi Clipboard:~/.config/hypr/scripts/clipboard.sh -show Clipboard -theme-str 'element { children: [element-text]; }' 
            ;;
        "󰄀  Screenshot")
            screenshot_func 
            ;;
        "  Session Options")
            session_options
            ;;
        "  Update System")
            foot --override=colors.alpha=1 --app-id=Update -e bash ~/.config/scripts/update
            ;;
        "  Settings")
            rice_settings
                    ;;
        "  Manual")
            manual_func
                    ;;
        *)
            echo "No option selected"
            ;;
    esac
}

theme_menu() {
   THEME_DIR="$HOME/.config/themes"

    # Menu options displayed in rofi
    THEMES=$(find "$THEME_DIR" -mindepth 1 -maxdepth 1 -type d -printf '%f\n')

    # Prompt user to choose an option
    chosen=$(echo -e "$THEMES" | rofi -config ~/.config/rofi/sysmenu.rasi -dmenu -theme-str 'mainbox {children: ["inputbar","listview" ];}'  -p "")
    
    if [[ -z "$chosen" ]]; then 
        exit 1 
    fi

   $HOME/.config/scripts/change-theme -c $chosen 

}



# Check for flags and validate input
if [[ $# -ne 1 ]]; then
    usage
fi

# Execute the appropriate function based on the provided flag
case "$1" in
    --drun)
        drun_launcher
        ;;
    --window)
        rofi \
        -show window \
        -theme ~/.config/rofi/window.rasi
        ;;

    --run)
        run_launcher
        ;;
    --menu)
        custom_menu
        ;;
    --widget_settings)
    	widget_settings
    	;;
     --rice_settings)
     	rice_settings
     	;;
     --system_menu|--sys_menu)
     	system_menu
     	;;
    *)
        usage
        ;;
esac
