#!/bin/bash

info() { gum style --foreground "#49A22C" -- <<< "➤ $1"; }

error() { gum style --foreground "#FF5555" -- <<< "✖ $1"; }

if [ -z "$1" ]; then
    echo "Usage: $0 [--set <File Location> | --reload]"
    exit 1
fi

case $1 in
    --set|-s)
        if [ -z "$2" ]; then
            error "Failed. Missing file location for --set option."
            exit 1
        fi
        if [[ "$2" != /* ]]; then
            filepath="$(pwd)/$2"
        else
            filepath="$2"
        fi
        ln -sf "$filepath" ~/.config/hypr/wallppr.png
		swww img "$filepath" --transition-fps 60 --transition-step 255 --transition-type wipe > /dev/null 2>&1 & disown
		sleep 1
        info "Wallpaper set to $filepath."
        ;;
    --reload|-r)
        pkill swww-deamon
        sleep 1
        nohup swww-daemon > /dev/null 2>&1 & disown
        eww reload > /dev/null 2>&1 & disown
        info "Wallpaper Reloaded"
        ;;
    --prompt|-p)
        THEMES=$(python ~/.config/hypr/scripts/wallpapers.py echoImageNames)
        chosen=$(printf '%s\n' "$THEMES" | gum choose --header 'Select a Wallpaper')
        python ~/.config/hypr/scripts/wallpapers.py changeWallpaper $chosen > /dev/null 2>&1
        info "Wallpaper Reloaded"
        ;;
    *)
        echo "Invalid option: $1"
        echo "Usage: $0 [--set <File Location> | --reload]"
        exit 1
        ;;
esac
